# Generated by Django 6.0.2 on 2026-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publishing',
            field=models.IntegerField(),
        ),
    ]
